package com.example.data.network

import com.example.BuildConfig
import com.example.domain.model.AiProvider
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

data class AiRequestOptions(
    val provider: AiProvider,
    val model: String,
    val apiKey: String,
    val baseUrl: String = provider.defaultBaseUrl,
    val systemPrompt: String = "",
    val temperature: Float = 0.7f,
    val topP: Float = 0.9f,
    val maxTokens: Int = 4096
)

class AiApiClient {
    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .build()

    suspend fun sendMessage(
        messages: List<Pair<String, String>>, // role to content
        options: AiRequestOptions
    ): String = withContext(Dispatchers.IO) {
        val effectiveApiKey = when {
            options.apiKey.isNotBlank() -> options.apiKey
            options.provider == AiProvider.GEMINI -> BuildConfig.GEMINI_API_KEY
            else -> ""
        }

        if (effectiveApiKey.isBlank()) {
            return@withContext "Error: No API key configured for ${options.provider.displayName}. Please configure your API Key in Settings."
        }

        val effectiveBaseUrl = options.baseUrl.ifBlank { options.provider.defaultBaseUrl }

        return@withContext try {
            when (options.provider) {
                AiProvider.GEMINI -> sendGeminiRequest(messages, options, effectiveApiKey, effectiveBaseUrl)
                AiProvider.CLAUDE -> sendClaudeRequest(messages, options, effectiveApiKey, effectiveBaseUrl)
                else -> sendOpenAiCompatibleRequest(messages, options, effectiveApiKey, effectiveBaseUrl)
            }
        } catch (e: Exception) {
            "API Request Error (${options.provider.displayName}): ${e.localizedMessage ?: e.message}"
        }
    }

    private fun sendGeminiRequest(
        messages: List<Pair<String, String>>,
        options: AiRequestOptions,
        apiKey: String,
        baseUrl: String
    ): String {
        val url = "${baseUrl.trimEnd('/')}/models/${options.model}:generateContent?key=$apiKey"

        val contentsArray = JSONArray()
        for ((role, content) in messages) {
            val geminiRole = if (role == "user") "user" else "model"
            val partObj = JSONObject().put("text", content)
            val partsArray = JSONArray().put(partObj)
            val contentObj = JSONObject()
                .put("role", geminiRole)
                .put("parts", partsArray)
            contentsArray.put(contentObj)
        }

        val rootObj = JSONObject().put("contents", contentsArray)

        if (options.systemPrompt.isNotBlank()) {
            val systemInstruction = JSONObject().put(
                "parts", JSONArray().put(JSONObject().put("text", options.systemPrompt))
            )
            rootObj.put("systemInstruction", systemInstruction)
        }

        val genConfig = JSONObject()
            .put("temperature", options.temperature)
            .put("topP", options.topP)
            .put("maxOutputTokens", options.maxTokens)
        rootObj.put("generationConfig", genConfig)

        val request = Request.Builder()
            .url(url)
            .post(rootObj.toString().toRequestBody("application/json".toMediaType()))
            .build()

        val response = client.newCall(request).execute()
        val responseBody = response.body?.string() ?: ""

        if (!response.isSuccessful) {
            val errJson = try { JSONObject(responseBody) } catch (e: Exception) { null }
            val errMsg = errJson?.optJSONObject("error")?.optString("message") ?: responseBody
            return "Gemini Error [${response.code}]: $errMsg"
        }

        val jsonResponse = JSONObject(responseBody)
        val candidates = jsonResponse.optJSONArray("candidates")
        if (candidates != null && candidates.length() > 0) {
            val parts = candidates.getJSONObject(0).optJSONObject("content")?.optJSONArray("parts")
            if (parts != null && parts.length() > 0) {
                return parts.getJSONObject(0).optString("text", "")
            }
        }

        return "No text response generated by Gemini."
    }

    private fun sendOpenAiCompatibleRequest(
        messages: List<Pair<String, String>>,
        options: AiRequestOptions,
        apiKey: String,
        baseUrl: String
    ): String {
        val endpoint = if (baseUrl.endsWith("/chat/completions")) baseUrl else "${baseUrl.trimEnd('/')}/chat/completions"

        val jsonMessages = JSONArray()
        if (options.systemPrompt.isNotBlank()) {
            jsonMessages.put(JSONObject().put("role", "system").put("content", options.systemPrompt))
        }

        for ((role, content) in messages) {
            jsonMessages.put(JSONObject().put("role", role).put("content", content))
        }

        val bodyObj = JSONObject()
            .put("model", options.model)
            .put("messages", jsonMessages)
            .put("temperature", options.temperature)
            .put("top_p", options.topP)
            .put("max_tokens", options.maxTokens)

        val requestBuilder = Request.Builder()
            .url(endpoint)
            .addHeader("Authorization", "Bearer $apiKey")
            .addHeader("Content-Type", "application/json")

        if (options.provider == AiProvider.OPENROUTER) {
            requestBuilder.addHeader("HTTP-Referer", "https://dragonfly.cli.ide")
            requestBuilder.addHeader("X-Title", "DragonflyCLI-IDE")
        }

        val request = requestBuilder
            .post(bodyObj.toString().toRequestBody("application/json".toMediaType()))
            .build()

        val response = client.newCall(request).execute()
        val responseBody = response.body?.string() ?: ""

        if (!response.isSuccessful) {
            val errJson = try { JSONObject(responseBody) } catch (e: Exception) { null }
            val errMsg = errJson?.optJSONObject("error")?.optString("message") ?: responseBody
            return "API Error [${response.code}]: $errMsg"
        }

        val jsonResponse = JSONObject(responseBody)
        val choices = jsonResponse.optJSONArray("choices")
        if (choices != null && choices.length() > 0) {
            val messageObj = choices.getJSONObject(0).optJSONObject("message")
            val text = messageObj?.optString("content") ?: ""
            return text
        }

        return "Empty response from server."
    }

    private fun sendClaudeRequest(
        messages: List<Pair<String, String>>,
        options: AiRequestOptions,
        apiKey: String,
        baseUrl: String
    ): String {
        val endpoint = if (baseUrl.endsWith("/messages")) baseUrl else "${baseUrl.trimEnd('/')}/messages"

        val jsonMessages = JSONArray()
        for ((role, content) in messages) {
            val claudeRole = if (role == "user") "user" else "assistant"
            jsonMessages.put(JSONObject().put("role", claudeRole).put("content", content))
        }

        val bodyObj = JSONObject()
            .put("model", options.model)
            .put("messages", jsonMessages)
            .put("max_tokens", options.maxTokens)

        if (options.systemPrompt.isNotBlank()) {
            bodyObj.put("system", options.systemPrompt)
        }

        val request = Request.Builder()
            .url(endpoint)
            .addHeader("x-api-key", apiKey)
            .addHeader("anthropic-version", "2023-06-01")
            .addHeader("Content-Type", "application/json")
            .post(bodyObj.toString().toRequestBody("application/json".toMediaType()))
            .build()

        val response = client.newCall(request).execute()
        val responseBody = response.body?.string() ?: ""

        if (!response.isSuccessful) {
            return "Claude Error [${response.code}]: $responseBody"
        }

        val jsonResponse = JSONObject(responseBody)
        val contentArray = jsonResponse.optJSONArray("content")
        if (contentArray != null && contentArray.length() > 0) {
            return contentArray.getJSONObject(0).optString("text", "")
        }

        return "Empty response from Claude."
    }
}
